### ISSUE TITLE
move Schönhage-Strassen in a real utils.h function

### ISSUE THREAD

**Issue by vrancurel** [scality/quadiron#68]
https://github.com/vrancurel/ntl/blob/ad47cc23d91abc1bfc20bce8b493db0b6151a4df/test/fft_utest.cpp#L134

**Comment by vrancurel** [comment]
could be useful one day for large polynomials multiplication (decode)

**Comment by slaperche-scality** [comment]
With the removal of GMP in https://github.com/scality/nttec/pull/195, I'm not sure if this issue is still relevant.

**Comment by slaperche-scality** [comment]
Schönhage-Strassen should be reimplement without GMP and as a standalone function.
